# name: Lint
# on:
#   pull_request:
#     paths:
#     - '**.md'
# jobs:
#     markdownlint-cli:
#         runs-on: ubuntu-latest
#         steps:
#         - uses: nosborn/github-action-markdown-cli@v1.1.1
#           with:
#             files: .
